### ISSUE TITLE
OH with Jarrod

### ISSUE THREAD

**Issue by lisaannyu** [berkeley-stat159/project-lambda#26]
@jarrodmillman 

Hi Jarrod,

Could we possibly meet with you as a group?  Three of us can't make your OH on Thursday.  
We are all free Wednesday and Thursday 4-5.  And 3 of us are free:
Wednesday 11-12, 2-3, 5-6
Thursday 2-3, 5-7:30
Friday 10-11

Hope one of those works for you!  We can also meet with you during lecture on Thursday if you prefer.  Thanks!

**Comment by jarrodmillman** [comment]
Friday 10-11 works best for me.  I think @matthew-brett will also be able to join us.  Make sure to have as clear an idea about what questions you want to ask from the data and your plan for the last few weeks of the semester as explicit as possible.  Also prepare a list of specific questions and technical issues if possible.  That will help us to assist you.

**Comment by lisaannyu** [comment]
Thank you!  See you then
