### ISSUE TITLE
Travis Failing

### ISSUE THREAD

**Issue by lisaannyu** [berkeley-stat159/project-lambda#46]
@jarrodmillman @rossbar 

Hi Jarrod and Ross,

I'm not sure why this Travis is failing.  Could you help me?

https://travis-ci.org/berkeley-stat159/project-lambda/jobs/95106536

Thanks!

**Comment by AlonDaks** [comment]
I think I fixed this issue. I had to update the .travis yml file @jarrodmillman or @rossbar can you confirm what I did makes sense: https://github.com/AlonDaks/project-lambda/commit/89aa9a5f1813e5ba0a55842ae4e4d7f08c0f37e9

**Comment by lisaannyu** [comment]
@AlonDaks Can I close this issue?

**Comment by AlonDaks** [comment]
Closed it
