### ISSUE TITLE
Np.Save / Load versus Hickle

### ISSUE THREAD

**Issue by AlonDaks** [berkeley-stat159/project-lambda#49]
Hi @matthew-brett @rossbar ,

Do you have advice for reading and writing ~7 Gb numpy arrays to and from disk? I've been using numpy's load and save but am wondering if you think this module would be an improvement: https://github.com/telegraphic/hickle?

Thanks,
Alon

**Comment by matthew-brett** [comment]
I don't have an opinion on hickle specifically.   HDF5 isn't a bad idea though.  It's pretty straightforward to save numpy arrays into hdf5 files - try the `h5py` module.

**Comment by AlonDaks** [comment]
Thank you
