### ISSUE TITLE
sharedmem==0.3.1 not found on travis ci

### ISSUE THREAD

**Issue by AlonDaks** [berkeley-stat159/project-lambda#59]
Hi @jarrodmillman @matthew-brett @rossbar,

I am using a package called sharedmem: https://pypi.python.org/pypi/sharedmem/0.3

The pip that travis is using cannot find this module: https://travis-ci.org/berkeley-stat159/project-lambda/jobs/95938234

Do you have any advice?

Thank you,
Alon

**Comment by matthew-brett** [comment]
I just set of builds for these packages to go up to the wheel repository you are using, so it should work shortly - try a rebuild in 20 minutes or so.

**Comment by AlonDaks** [comment]
Thank you for the quick follow up :+1:

**Comment by matthew-brett** [comment]
Alon - can you close this one if all done?

**Comment by AlonDaks** [comment]
Yes sorry.
