### ISSUE TITLE
Very large data

### ISSUE THREAD

**Issue by AlonDaks** [berkeley-stat159/project-lambda#69]
Hi @jarrodmillman @rossbar 

Data for each subject is ~7 GBs. This is the result of me concatenating all 8 runs together. Also, note that when I load in the original data the values in the 4D array are integers. When I convert the 4D array to floats the size of the array jumps to 30 GBs. Does this sound right? To get this all working I'm running the code on an amazon machine with 120 GBs of memory. I want to confirm that you will be able to run our code on a machine with sufficient capabilities as implied earlier in the semester. 

Do you have suggestions for how in our analysis we can trim the size of the entire array (maybe averaging values of neighboring voxels and creating a new 4D array of lower spatial resolution) or ways I can compress this object?

Thank you,
Alon

**Comment by rossbar** [comment]
Just out of curiosity, what is the type of the original data? I'm surprised that converting to floats essentially quadruples the size of the array; the only way that makes sense is if the data is originally 16-bit integers and you're converting to 64-bit floats (np.float defaults to 64-bit floats on 64-bit machines I believe; at least on all my machines).

I believe I have access to a server that should be sufficient to run your project.

**Comment by AlonDaks** [comment]
The original data comes in as 16-bit integers. I think your right that it is converting to 64-bit floats. What do you think is safe to convert to: 16-bit floats or 32-bit floats?

**Comment by rossbar** [comment]
You should be able to use 32-bit floats

**Comment by AlonDaks** [comment]
OK - thank you
